### ISSUE TITLE
Allow formatted dates as valid values for TIMESTAMP columns

### ISSUE THREAD

**Issue by chuym** [Incroud/cassanova#13]
http://www.datastax.com/documentation/cql/3.0/cql/cql_reference/timestamp_type_r.html

> Values for the timestamp type are encoded as 64-bit signed integers representing a number of milliseconds since the standard base time known as the epoch: January 1 1970 at 00:00:00 GMT. A timestamp type can be entered as an integer for CQL input, or as a string literals in any of the following ISO 8601 formats:  
yyyy-mm-dd HH:mm
yyyy-mm-dd HH:mm:ss
yyyy-mm-dd HH:mmZ
yyyy-mm-dd HH:mm:ssZ
yyyy-mm-dd'T'HH:mm
yyyy-mm-dd'T'HH:mmZ
yyyy-mm-dd'T'HH:mm:ss
yyyy-mm-dd'T'HH:mm:ssZ
yyyy-mm-dd
yyyy-mm-ddZ

Right now, cassanova only supports for UNIX timestamps as values, sending something else and the value doesn't get wrapped correctly and the insert/update fails

**Comment by adamcahan** [comment]
I was wondering about this as well, actually.

**Comment by keswanikaran** [comment]
@chuym It was fixed such that you can pass either iso or javascript date. Please test. Latest version is in npm.
